// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux && attach

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type barrierAdmission struct {
	_                structs.HostLayout
	Generation       uint64
	Birth            uint64
	ParentGeneration uint64
	ParentNsDev      uint64
	ParentNsIno      uint64
	ParentPid        uint32
	Target           uint32
	Rule             uint32
	Threads          uint32
	Kind             uint8
	Mode             uint8
	Propagate        uint8
	LeaderGone       uint8
	Reserved         [4]uint8
}

type barrierBinding struct {
	_           structs.HostLayout
	Fd          int32
	Reserved    uint32
	Generation  uint64
	Inode       uint64
	Occupancy   uint64
	NetIno      uint64
	Opened      uint64
	Local       [16]uint8
	Peer        [16]uint8
	Lport       uint16
	Dport       uint16
	Ends        uint8
	EndsPadding [3]uint8
}

type barrierCall struct {
	_           structs.HostLayout
	Ssl         uint64
	Buf         uint64
	Cap         uint64
	Pcount      uint64
	Generation  uint64
	Sequence    uint64
	Func        uint32
	Fd          int32
	Fds         uint8
	_           [7]byte
	Socket      uint64
	SocketIno   uint64
	SocketGen   uint64
	SocketOcc   uint64
	NetIno      uint64
	Opened      uint64
	Local       [16]uint8
	Peer        [16]uint8
	Lport       uint16
	Dport       uint16
	SocketFd    int32
	Sockets     uint8
	Ends        uint8
	Outcome     uint8
	Io          uint8
	Dir         uint8
	Count       uint8
	Early       uint8
	Deferred    uint8
	Live        uint8
	Nested      uint8
	LivePadding [6]uint8
	Occupancy   uint64
	Number      uint64
}

type barrierHandleKey struct {
	_        structs.HostLayout
	NsDev    uint64
	NsIno    uint64
	Pid      uint32
	Reserved uint32
	Ssl      uint64
}

type barrierHolding struct {
	_       structs.HostLayout
	Entries uint8
	Events  uint8
	Padding [6]uint8
}

type barrierInstanceKey struct {
	_        structs.HostLayout
	NsDev    uint64
	NsIno    uint64
	Pid      uint32
	Reserved uint32
}

type barrierObsNs struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

type barrierOccupancy struct {
	_                  structs.HostLayout
	Id                 uint64
	Generation         uint64
	Unlocated          uint64
	Sent               uint64
	Received           uint64
	DroppedSent        uint64
	DroppedReceived    uint64
	BusySent           uint64
	BusyReceived       uint64
	OverlappedSent     uint8
	OverlappedReceived uint8
	Born               uint8
	Padding            [5]uint8
}

type barrierOperation struct {
	_           structs.HostLayout
	Call        uint64
	Entered     uint64
	Socket      uint64
	Ino         uint64
	Gen         uint64
	Syscall     uint32
	Fd          int32
	Family      uint8
	Outcome     uint8
	Live        uint8
	SocketKnown uint8
	_           [4]byte
	Occupancy   uint64
	Local       [16]uint8
	Peer        [16]uint8
	NetIno      uint64
	Opened      uint64
	Lport       uint16
	Dport       uint16
	Ends        uint8
	_           [3]byte
}

type barrierReadBarrierState struct {
	_          structs.HostLayout
	Generation uint64
	State      uint32
	Padding    uint32
}

type barrierSocketIdent struct {
	_    structs.HostLayout
	Sock uint64
	Ino  uint64
}

type barrierSocketKey struct {
	_     structs.HostLayout
	NsDev uint64
	NsIno uint64
	Pid   uint32
	Fd    int32
}

type barrierSocketLife struct {
	_          structs.HostLayout
	Generation uint64
	Opened     uint64
}

type barrierSocketLifeKernel struct {
	_          structs.HostLayout
	Generation uint64
}

type barrierUnmatched struct {
	_     structs.HostLayout
	First uint64
	Last  uint64
	Ssl   uint64
	Pid   uint32
	Tid   uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	barrierMapAllowedProcesses     = "allowed_processes"
	barrierMapAttempts             = "attempts"
	barrierMapBindings             = "bindings"
	barrierMapCaptureLive          = "capture_live"
	barrierMapDiscovered           = "discovered"
	barrierMapDiscoveries          = "discoveries"
	barrierMapEvents               = "events"
	barrierMapForking              = "forking"
	barrierMapGenerations          = "generations"
	barrierMapHandles              = "handles"
	barrierMapHolders              = "holders"
	barrierMapInflight             = "inflight"
	barrierMapNamespaces           = "namespaces"
	barrierMapOccupancies          = "occupancies"
	barrierMapOccupancyIds         = "occupancy_ids"
	barrierMapOperations           = "operations"
	barrierMapReadBarrier          = "read_barrier"
	barrierMapReads                = "reads"
	barrierMapSequences            = "sequences"
	barrierMapSockets              = "sockets"
	barrierMapStats                = "stats"
	barrierMapUnlocated            = "unlocated"
	barrierMapUnmatchedAt          = "unmatched_at"
	barrierMapUnmeasurable         = "unmeasurable"
	barrierProgObsAcceptReturn     = "obs_accept_return"
	barrierProgObsClearEntry       = "obs_clear_entry"
	barrierProgObsClose            = "obs_close"
	barrierProgObsConnect          = "obs_connect"
	barrierProgObsDup2             = "obs_dup2"
	barrierProgObsExec             = "obs_exec"
	barrierProgObsExit             = "obs_exit"
	barrierProgObsFork             = "obs_fork"
	barrierProgObsForkEntry        = "obs_fork_entry"
	barrierProgObsForkReturn       = "obs_fork_return"
	barrierProgObsFreeEntry        = "obs_free_entry"
	barrierProgObsInet6Recvmsg     = "obs_inet6_recvmsg"
	barrierProgObsInet6Sendmsg     = "obs_inet6_sendmsg"
	barrierProgObsInetRecvmsg      = "obs_inet_recvmsg"
	barrierProgObsInetRelease      = "obs_inet_release"
	barrierProgObsInetSendmsg      = "obs_inet_sendmsg"
	barrierProgObsNewReturn        = "obs_new_return"
	barrierProgObsRead             = "obs_read"
	barrierProgObsReadEarlyEntry   = "obs_read_early_entry"
	barrierProgObsReadEarlyReturn  = "obs_read_early_return"
	barrierProgObsReadEntry        = "obs_read_entry"
	barrierProgObsReadExEntry      = "obs_read_ex_entry"
	barrierProgObsReadExReturn     = "obs_read_ex_return"
	barrierProgObsReadReturn       = "obs_read_return"
	barrierProgObsReadv            = "obs_readv"
	barrierProgObsRecvfrom         = "obs_recvfrom"
	barrierProgObsRecvmsg          = "obs_recvmsg"
	barrierProgObsRwVerifyArea     = "obs_rw_verify_area"
	barrierProgObsSendfile         = "obs_sendfile"
	barrierProgObsSendmsg          = "obs_sendmsg"
	barrierProgObsSendto           = "obs_sendto"
	barrierProgObsSocketReturn     = "obs_socket_return"
	barrierProgObsSysEnter         = "obs_sys_enter"
	barrierProgObsSysExit          = "obs_sys_exit"
	barrierProgObsWrite            = "obs_write"
	barrierProgObsWriteEarlyEntry  = "obs_write_early_entry"
	barrierProgObsWriteEarlyReturn = "obs_write_early_return"
	barrierProgObsWriteEntry       = "obs_write_entry"
	barrierProgObsWriteEx2Entry    = "obs_write_ex2_entry"
	barrierProgObsWriteEx2Return   = "obs_write_ex2_return"
	barrierProgObsWriteExEntry     = "obs_write_ex_entry"
	barrierProgObsWriteExReturn    = "obs_write_ex_return"
	barrierProgObsWriteReturn      = "obs_write_return"
	barrierProgObsWritev           = "obs_writev"
)

// loadBarrier returns the embedded CollectionSpec for barrier.
func loadBarrier() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BarrierBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load barrier: %w", err)
	}

	return spec, err
}

// loadBarrierObjects loads barrier and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*barrierObjects
//	*barrierPrograms
//	*barrierMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBarrierObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBarrier()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// barrierSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type barrierSpecs struct {
	barrierProgramSpecs
	barrierMapSpecs
	barrierVariableSpecs
}

// barrierProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type barrierProgramSpecs struct {
	ObsAcceptReturn     *ebpf.ProgramSpec `ebpf:"obs_accept_return"`
	ObsClearEntry       *ebpf.ProgramSpec `ebpf:"obs_clear_entry"`
	ObsClose            *ebpf.ProgramSpec `ebpf:"obs_close"`
	ObsConnect          *ebpf.ProgramSpec `ebpf:"obs_connect"`
	ObsDup2             *ebpf.ProgramSpec `ebpf:"obs_dup2"`
	ObsExec             *ebpf.ProgramSpec `ebpf:"obs_exec"`
	ObsExit             *ebpf.ProgramSpec `ebpf:"obs_exit"`
	ObsFork             *ebpf.ProgramSpec `ebpf:"obs_fork"`
	ObsForkEntry        *ebpf.ProgramSpec `ebpf:"obs_fork_entry"`
	ObsForkReturn       *ebpf.ProgramSpec `ebpf:"obs_fork_return"`
	ObsFreeEntry        *ebpf.ProgramSpec `ebpf:"obs_free_entry"`
	ObsInet6Recvmsg     *ebpf.ProgramSpec `ebpf:"obs_inet6_recvmsg"`
	ObsInet6Sendmsg     *ebpf.ProgramSpec `ebpf:"obs_inet6_sendmsg"`
	ObsInetRecvmsg      *ebpf.ProgramSpec `ebpf:"obs_inet_recvmsg"`
	ObsInetRelease      *ebpf.ProgramSpec `ebpf:"obs_inet_release"`
	ObsInetSendmsg      *ebpf.ProgramSpec `ebpf:"obs_inet_sendmsg"`
	ObsNewReturn        *ebpf.ProgramSpec `ebpf:"obs_new_return"`
	ObsRead             *ebpf.ProgramSpec `ebpf:"obs_read"`
	ObsReadEarlyEntry   *ebpf.ProgramSpec `ebpf:"obs_read_early_entry"`
	ObsReadEarlyReturn  *ebpf.ProgramSpec `ebpf:"obs_read_early_return"`
	ObsReadEntry        *ebpf.ProgramSpec `ebpf:"obs_read_entry"`
	ObsReadExEntry      *ebpf.ProgramSpec `ebpf:"obs_read_ex_entry"`
	ObsReadExReturn     *ebpf.ProgramSpec `ebpf:"obs_read_ex_return"`
	ObsReadReturn       *ebpf.ProgramSpec `ebpf:"obs_read_return"`
	ObsReadv            *ebpf.ProgramSpec `ebpf:"obs_readv"`
	ObsRecvfrom         *ebpf.ProgramSpec `ebpf:"obs_recvfrom"`
	ObsRecvmsg          *ebpf.ProgramSpec `ebpf:"obs_recvmsg"`
	ObsRwVerifyArea     *ebpf.ProgramSpec `ebpf:"obs_rw_verify_area"`
	ObsSendfile         *ebpf.ProgramSpec `ebpf:"obs_sendfile"`
	ObsSendmsg          *ebpf.ProgramSpec `ebpf:"obs_sendmsg"`
	ObsSendto           *ebpf.ProgramSpec `ebpf:"obs_sendto"`
	ObsSocketReturn     *ebpf.ProgramSpec `ebpf:"obs_socket_return"`
	ObsSysEnter         *ebpf.ProgramSpec `ebpf:"obs_sys_enter"`
	ObsSysExit          *ebpf.ProgramSpec `ebpf:"obs_sys_exit"`
	ObsWrite            *ebpf.ProgramSpec `ebpf:"obs_write"`
	ObsWriteEarlyEntry  *ebpf.ProgramSpec `ebpf:"obs_write_early_entry"`
	ObsWriteEarlyReturn *ebpf.ProgramSpec `ebpf:"obs_write_early_return"`
	ObsWriteEntry       *ebpf.ProgramSpec `ebpf:"obs_write_entry"`
	ObsWriteEx2Entry    *ebpf.ProgramSpec `ebpf:"obs_write_ex2_entry"`
	ObsWriteEx2Return   *ebpf.ProgramSpec `ebpf:"obs_write_ex2_return"`
	ObsWriteExEntry     *ebpf.ProgramSpec `ebpf:"obs_write_ex_entry"`
	ObsWriteExReturn    *ebpf.ProgramSpec `ebpf:"obs_write_ex_return"`
	ObsWriteReturn      *ebpf.ProgramSpec `ebpf:"obs_write_return"`
	ObsWritev           *ebpf.ProgramSpec `ebpf:"obs_writev"`
}

// barrierMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type barrierMapSpecs struct {
	AllowedProcesses *ebpf.MapSpec `ebpf:"allowed_processes"`
	Attempts         *ebpf.MapSpec `ebpf:"attempts"`
	Bindings         *ebpf.MapSpec `ebpf:"bindings"`
	CaptureLive      *ebpf.MapSpec `ebpf:"capture_live"`
	Discovered       *ebpf.MapSpec `ebpf:"discovered"`
	Discoveries      *ebpf.MapSpec `ebpf:"discoveries"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	Forking          *ebpf.MapSpec `ebpf:"forking"`
	Generations      *ebpf.MapSpec `ebpf:"generations"`
	Handles          *ebpf.MapSpec `ebpf:"handles"`
	Holders          *ebpf.MapSpec `ebpf:"holders"`
	Inflight         *ebpf.MapSpec `ebpf:"inflight"`
	Namespaces       *ebpf.MapSpec `ebpf:"namespaces"`
	Occupancies      *ebpf.MapSpec `ebpf:"occupancies"`
	OccupancyIds     *ebpf.MapSpec `ebpf:"occupancy_ids"`
	Operations       *ebpf.MapSpec `ebpf:"operations"`
	ReadBarrier      *ebpf.MapSpec `ebpf:"read_barrier"`
	Reads            *ebpf.MapSpec `ebpf:"reads"`
	Sequences        *ebpf.MapSpec `ebpf:"sequences"`
	Sockets          *ebpf.MapSpec `ebpf:"sockets"`
	Stats            *ebpf.MapSpec `ebpf:"stats"`
	Unlocated        *ebpf.MapSpec `ebpf:"unlocated"`
	UnmatchedAt      *ebpf.MapSpec `ebpf:"unmatched_at"`
	Unmeasurable     *ebpf.MapSpec `ebpf:"unmeasurable"`
}

// barrierVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type barrierVariableSpecs struct {
}

// barrierObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBarrierObjects or ebpf.CollectionSpec.LoadAndAssign.
type barrierObjects struct {
	barrierPrograms
	barrierMaps
	barrierVariables
}

func (o *barrierObjects) Close() error {
	return _BarrierClose(
		&o.barrierPrograms,
		&o.barrierMaps,
	)
}

// barrierMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBarrierObjects or ebpf.CollectionSpec.LoadAndAssign.
type barrierMaps struct {
	AllowedProcesses *ebpf.Map `ebpf:"allowed_processes"`
	Attempts         *ebpf.Map `ebpf:"attempts"`
	Bindings         *ebpf.Map `ebpf:"bindings"`
	CaptureLive      *ebpf.Map `ebpf:"capture_live"`
	Discovered       *ebpf.Map `ebpf:"discovered"`
	Discoveries      *ebpf.Map `ebpf:"discoveries"`
	Events           *ebpf.Map `ebpf:"events"`
	Forking          *ebpf.Map `ebpf:"forking"`
	Generations      *ebpf.Map `ebpf:"generations"`
	Handles          *ebpf.Map `ebpf:"handles"`
	Holders          *ebpf.Map `ebpf:"holders"`
	Inflight         *ebpf.Map `ebpf:"inflight"`
	Namespaces       *ebpf.Map `ebpf:"namespaces"`
	Occupancies      *ebpf.Map `ebpf:"occupancies"`
	OccupancyIds     *ebpf.Map `ebpf:"occupancy_ids"`
	Operations       *ebpf.Map `ebpf:"operations"`
	ReadBarrier      *ebpf.Map `ebpf:"read_barrier"`
	Reads            *ebpf.Map `ebpf:"reads"`
	Sequences        *ebpf.Map `ebpf:"sequences"`
	Sockets          *ebpf.Map `ebpf:"sockets"`
	Stats            *ebpf.Map `ebpf:"stats"`
	Unlocated        *ebpf.Map `ebpf:"unlocated"`
	UnmatchedAt      *ebpf.Map `ebpf:"unmatched_at"`
	Unmeasurable     *ebpf.Map `ebpf:"unmeasurable"`
}

func (m *barrierMaps) Close() error {
	return _BarrierClose(
		m.AllowedProcesses,
		m.Attempts,
		m.Bindings,
		m.CaptureLive,
		m.Discovered,
		m.Discoveries,
		m.Events,
		m.Forking,
		m.Generations,
		m.Handles,
		m.Holders,
		m.Inflight,
		m.Namespaces,
		m.Occupancies,
		m.OccupancyIds,
		m.Operations,
		m.ReadBarrier,
		m.Reads,
		m.Sequences,
		m.Sockets,
		m.Stats,
		m.Unlocated,
		m.UnmatchedAt,
		m.Unmeasurable,
	)
}

// barrierVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBarrierObjects or ebpf.CollectionSpec.LoadAndAssign.
type barrierVariables struct {
}

// barrierPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBarrierObjects or ebpf.CollectionSpec.LoadAndAssign.
type barrierPrograms struct {
	ObsAcceptReturn     *ebpf.Program `ebpf:"obs_accept_return"`
	ObsClearEntry       *ebpf.Program `ebpf:"obs_clear_entry"`
	ObsClose            *ebpf.Program `ebpf:"obs_close"`
	ObsConnect          *ebpf.Program `ebpf:"obs_connect"`
	ObsDup2             *ebpf.Program `ebpf:"obs_dup2"`
	ObsExec             *ebpf.Program `ebpf:"obs_exec"`
	ObsExit             *ebpf.Program `ebpf:"obs_exit"`
	ObsFork             *ebpf.Program `ebpf:"obs_fork"`
	ObsForkEntry        *ebpf.Program `ebpf:"obs_fork_entry"`
	ObsForkReturn       *ebpf.Program `ebpf:"obs_fork_return"`
	ObsFreeEntry        *ebpf.Program `ebpf:"obs_free_entry"`
	ObsInet6Recvmsg     *ebpf.Program `ebpf:"obs_inet6_recvmsg"`
	ObsInet6Sendmsg     *ebpf.Program `ebpf:"obs_inet6_sendmsg"`
	ObsInetRecvmsg      *ebpf.Program `ebpf:"obs_inet_recvmsg"`
	ObsInetRelease      *ebpf.Program `ebpf:"obs_inet_release"`
	ObsInetSendmsg      *ebpf.Program `ebpf:"obs_inet_sendmsg"`
	ObsNewReturn        *ebpf.Program `ebpf:"obs_new_return"`
	ObsRead             *ebpf.Program `ebpf:"obs_read"`
	ObsReadEarlyEntry   *ebpf.Program `ebpf:"obs_read_early_entry"`
	ObsReadEarlyReturn  *ebpf.Program `ebpf:"obs_read_early_return"`
	ObsReadEntry        *ebpf.Program `ebpf:"obs_read_entry"`
	ObsReadExEntry      *ebpf.Program `ebpf:"obs_read_ex_entry"`
	ObsReadExReturn     *ebpf.Program `ebpf:"obs_read_ex_return"`
	ObsReadReturn       *ebpf.Program `ebpf:"obs_read_return"`
	ObsReadv            *ebpf.Program `ebpf:"obs_readv"`
	ObsRecvfrom         *ebpf.Program `ebpf:"obs_recvfrom"`
	ObsRecvmsg          *ebpf.Program `ebpf:"obs_recvmsg"`
	ObsRwVerifyArea     *ebpf.Program `ebpf:"obs_rw_verify_area"`
	ObsSendfile         *ebpf.Program `ebpf:"obs_sendfile"`
	ObsSendmsg          *ebpf.Program `ebpf:"obs_sendmsg"`
	ObsSendto           *ebpf.Program `ebpf:"obs_sendto"`
	ObsSocketReturn     *ebpf.Program `ebpf:"obs_socket_return"`
	ObsSysEnter         *ebpf.Program `ebpf:"obs_sys_enter"`
	ObsSysExit          *ebpf.Program `ebpf:"obs_sys_exit"`
	ObsWrite            *ebpf.Program `ebpf:"obs_write"`
	ObsWriteEarlyEntry  *ebpf.Program `ebpf:"obs_write_early_entry"`
	ObsWriteEarlyReturn *ebpf.Program `ebpf:"obs_write_early_return"`
	ObsWriteEntry       *ebpf.Program `ebpf:"obs_write_entry"`
	ObsWriteEx2Entry    *ebpf.Program `ebpf:"obs_write_ex2_entry"`
	ObsWriteEx2Return   *ebpf.Program `ebpf:"obs_write_ex2_return"`
	ObsWriteExEntry     *ebpf.Program `ebpf:"obs_write_ex_entry"`
	ObsWriteExReturn    *ebpf.Program `ebpf:"obs_write_ex_return"`
	ObsWriteReturn      *ebpf.Program `ebpf:"obs_write_return"`
	ObsWritev           *ebpf.Program `ebpf:"obs_writev"`
}

func (p *barrierPrograms) Close() error {
	return _BarrierClose(
		p.ObsAcceptReturn,
		p.ObsClearEntry,
		p.ObsClose,
		p.ObsConnect,
		p.ObsDup2,
		p.ObsExec,
		p.ObsExit,
		p.ObsFork,
		p.ObsForkEntry,
		p.ObsForkReturn,
		p.ObsFreeEntry,
		p.ObsInet6Recvmsg,
		p.ObsInet6Sendmsg,
		p.ObsInetRecvmsg,
		p.ObsInetRelease,
		p.ObsInetSendmsg,
		p.ObsNewReturn,
		p.ObsRead,
		p.ObsReadEarlyEntry,
		p.ObsReadEarlyReturn,
		p.ObsReadEntry,
		p.ObsReadExEntry,
		p.ObsReadExReturn,
		p.ObsReadReturn,
		p.ObsReadv,
		p.ObsRecvfrom,
		p.ObsRecvmsg,
		p.ObsRwVerifyArea,
		p.ObsSendfile,
		p.ObsSendmsg,
		p.ObsSendto,
		p.ObsSocketReturn,
		p.ObsSysEnter,
		p.ObsSysExit,
		p.ObsWrite,
		p.ObsWriteEarlyEntry,
		p.ObsWriteEarlyReturn,
		p.ObsWriteEntry,
		p.ObsWriteEx2Entry,
		p.ObsWriteEx2Return,
		p.ObsWriteExEntry,
		p.ObsWriteExReturn,
		p.ObsWriteReturn,
		p.ObsWritev,
	)
}

func _BarrierClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed barrier_x86_bpfel.o
var _BarrierBytes []byte
