// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type metaAdmission struct {
	_                structs.HostLayout
	Generation       uint64
	Birth            uint64
	ParentGeneration uint64
	ParentNsDev      uint64
	ParentNsIno      uint64
	ParentPid        uint32
	Target           uint32
	Rule             uint32
	Threads          uint32
	Kind             uint8
	Mode             uint8
	Propagate        uint8
	LeaderGone       uint8
	Reserved         [4]uint8
}

type metaBinding struct {
	_           structs.HostLayout
	Fd          int32
	Reserved    uint32
	Generation  uint64
	Inode       uint64
	Occupancy   uint64
	NetIno      uint64
	Opened      uint64
	Local       [16]uint8
	Peer        [16]uint8
	Lport       uint16
	Dport       uint16
	Ends        uint8
	EndsPadding [3]uint8
}

type metaCall struct {
	_           structs.HostLayout
	Ssl         uint64
	Buf         uint64
	Cap         uint64
	Pcount      uint64
	Generation  uint64
	Sequence    uint64
	Func        uint32
	Fd          int32
	Fds         uint8
	_           [7]byte
	Socket      uint64
	SocketIno   uint64
	SocketGen   uint64
	SocketOcc   uint64
	NetIno      uint64
	Opened      uint64
	Local       [16]uint8
	Peer        [16]uint8
	Lport       uint16
	Dport       uint16
	SocketFd    int32
	Sockets     uint8
	Ends        uint8
	Outcome     uint8
	Io          uint8
	Dir         uint8
	Count       uint8
	Early       uint8
	Deferred    uint8
	Live        uint8
	LivePadding [3]uint8
	_           [4]byte
}

type metaHandleKey struct {
	_        structs.HostLayout
	NsDev    uint64
	NsIno    uint64
	Pid      uint32
	Reserved uint32
	Ssl      uint64
}

type metaInstanceKey struct {
	_        structs.HostLayout
	NsDev    uint64
	NsIno    uint64
	Pid      uint32
	Reserved uint32
}

type metaObsNs struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

type metaOperation struct {
	_           structs.HostLayout
	Call        uint64
	Entered     uint64
	Socket      uint64
	Ino         uint64
	Gen         uint64
	Syscall     uint32
	Fd          int32
	Family      uint8
	Outcome     uint8
	Live        uint8
	SocketKnown uint8
	_           [4]byte
	Occupancy   uint64
	Local       [16]uint8
	Peer        [16]uint8
	NetIno      uint64
	Opened      uint64
	Lport       uint16
	Dport       uint16
	Ends        uint8
	_           [3]byte
}

type metaSocketIdent struct {
	_    structs.HostLayout
	Sock uint64
	Ino  uint64
}

type metaSocketKey struct {
	_     structs.HostLayout
	NsDev uint64
	NsIno uint64
	Pid   uint32
	Fd    int32
}

type metaSocketLife struct {
	_          structs.HostLayout
	Generation uint64
	Opened     uint64
}

type metaSocketLifeKernel struct {
	_          structs.HostLayout
	Generation uint64
}

type metaUnmatched struct {
	_     structs.HostLayout
	First uint64
	Last  uint64
	Ssl   uint64
	Pid   uint32
	Tid   uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	metaMapAllowedProcesses     = "allowed_processes"
	metaMapAttempts             = "attempts"
	metaMapBindings             = "bindings"
	metaMapDiscovered           = "discovered"
	metaMapDiscoveries          = "discoveries"
	metaMapEvents               = "events"
	metaMapForking              = "forking"
	metaMapGenerations          = "generations"
	metaMapHandles              = "handles"
	metaMapInflight             = "inflight"
	metaMapNamespaces           = "namespaces"
	metaMapOperations           = "operations"
	metaMapSequences            = "sequences"
	metaMapSockets              = "sockets"
	metaMapStats                = "stats"
	metaMapUnmatchedAt          = "unmatched_at"
	metaMapUnmeasurable         = "unmeasurable"
	metaProgObsAcceptReturn     = "obs_accept_return"
	metaProgObsClose            = "obs_close"
	metaProgObsConnect          = "obs_connect"
	metaProgObsDup2             = "obs_dup2"
	metaProgObsExec             = "obs_exec"
	metaProgObsExit             = "obs_exit"
	metaProgObsFork             = "obs_fork"
	metaProgObsForkEntry        = "obs_fork_entry"
	metaProgObsForkReturn       = "obs_fork_return"
	metaProgObsFreeEntry        = "obs_free_entry"
	metaProgObsInet6Recvmsg     = "obs_inet6_recvmsg"
	metaProgObsInet6Sendmsg     = "obs_inet6_sendmsg"
	metaProgObsInetRecvmsg      = "obs_inet_recvmsg"
	metaProgObsInetSendmsg      = "obs_inet_sendmsg"
	metaProgObsRead             = "obs_read"
	metaProgObsReadEarlyEntry   = "obs_read_early_entry"
	metaProgObsReadEarlyReturn  = "obs_read_early_return"
	metaProgObsReadEntry        = "obs_read_entry"
	metaProgObsReadExEntry      = "obs_read_ex_entry"
	metaProgObsReadExReturn     = "obs_read_ex_return"
	metaProgObsReadReturn       = "obs_read_return"
	metaProgObsReadv            = "obs_readv"
	metaProgObsRecvfrom         = "obs_recvfrom"
	metaProgObsRecvmsg          = "obs_recvmsg"
	metaProgObsRwVerifyArea     = "obs_rw_verify_area"
	metaProgObsSendmsg          = "obs_sendmsg"
	metaProgObsSendto           = "obs_sendto"
	metaProgObsSocketReturn     = "obs_socket_return"
	metaProgObsSysEnter         = "obs_sys_enter"
	metaProgObsSysExit          = "obs_sys_exit"
	metaProgObsWrite            = "obs_write"
	metaProgObsWriteEarlyEntry  = "obs_write_early_entry"
	metaProgObsWriteEarlyReturn = "obs_write_early_return"
	metaProgObsWriteEntry       = "obs_write_entry"
	metaProgObsWriteEx2Entry    = "obs_write_ex2_entry"
	metaProgObsWriteEx2Return   = "obs_write_ex2_return"
	metaProgObsWriteExEntry     = "obs_write_ex_entry"
	metaProgObsWriteExReturn    = "obs_write_ex_return"
	metaProgObsWriteReturn      = "obs_write_return"
	metaProgObsWritev           = "obs_writev"
)

// loadMeta returns the embedded CollectionSpec for meta.
func loadMeta() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MetaBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load meta: %w", err)
	}

	return spec, err
}

// loadMetaObjects loads meta and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*metaObjects
//	*metaPrograms
//	*metaMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMetaObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadMeta()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// metaSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metaSpecs struct {
	metaProgramSpecs
	metaMapSpecs
	metaVariableSpecs
}

// metaProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metaProgramSpecs struct {
	ObsAcceptReturn     *ebpf.ProgramSpec `ebpf:"obs_accept_return"`
	ObsClose            *ebpf.ProgramSpec `ebpf:"obs_close"`
	ObsConnect          *ebpf.ProgramSpec `ebpf:"obs_connect"`
	ObsDup2             *ebpf.ProgramSpec `ebpf:"obs_dup2"`
	ObsExec             *ebpf.ProgramSpec `ebpf:"obs_exec"`
	ObsExit             *ebpf.ProgramSpec `ebpf:"obs_exit"`
	ObsFork             *ebpf.ProgramSpec `ebpf:"obs_fork"`
	ObsForkEntry        *ebpf.ProgramSpec `ebpf:"obs_fork_entry"`
	ObsForkReturn       *ebpf.ProgramSpec `ebpf:"obs_fork_return"`
	ObsFreeEntry        *ebpf.ProgramSpec `ebpf:"obs_free_entry"`
	ObsInet6Recvmsg     *ebpf.ProgramSpec `ebpf:"obs_inet6_recvmsg"`
	ObsInet6Sendmsg     *ebpf.ProgramSpec `ebpf:"obs_inet6_sendmsg"`
	ObsInetRecvmsg      *ebpf.ProgramSpec `ebpf:"obs_inet_recvmsg"`
	ObsInetSendmsg      *ebpf.ProgramSpec `ebpf:"obs_inet_sendmsg"`
	ObsRead             *ebpf.ProgramSpec `ebpf:"obs_read"`
	ObsReadEarlyEntry   *ebpf.ProgramSpec `ebpf:"obs_read_early_entry"`
	ObsReadEarlyReturn  *ebpf.ProgramSpec `ebpf:"obs_read_early_return"`
	ObsReadEntry        *ebpf.ProgramSpec `ebpf:"obs_read_entry"`
	ObsReadExEntry      *ebpf.ProgramSpec `ebpf:"obs_read_ex_entry"`
	ObsReadExReturn     *ebpf.ProgramSpec `ebpf:"obs_read_ex_return"`
	ObsReadReturn       *ebpf.ProgramSpec `ebpf:"obs_read_return"`
	ObsReadv            *ebpf.ProgramSpec `ebpf:"obs_readv"`
	ObsRecvfrom         *ebpf.ProgramSpec `ebpf:"obs_recvfrom"`
	ObsRecvmsg          *ebpf.ProgramSpec `ebpf:"obs_recvmsg"`
	ObsRwVerifyArea     *ebpf.ProgramSpec `ebpf:"obs_rw_verify_area"`
	ObsSendmsg          *ebpf.ProgramSpec `ebpf:"obs_sendmsg"`
	ObsSendto           *ebpf.ProgramSpec `ebpf:"obs_sendto"`
	ObsSocketReturn     *ebpf.ProgramSpec `ebpf:"obs_socket_return"`
	ObsSysEnter         *ebpf.ProgramSpec `ebpf:"obs_sys_enter"`
	ObsSysExit          *ebpf.ProgramSpec `ebpf:"obs_sys_exit"`
	ObsWrite            *ebpf.ProgramSpec `ebpf:"obs_write"`
	ObsWriteEarlyEntry  *ebpf.ProgramSpec `ebpf:"obs_write_early_entry"`
	ObsWriteEarlyReturn *ebpf.ProgramSpec `ebpf:"obs_write_early_return"`
	ObsWriteEntry       *ebpf.ProgramSpec `ebpf:"obs_write_entry"`
	ObsWriteEx2Entry    *ebpf.ProgramSpec `ebpf:"obs_write_ex2_entry"`
	ObsWriteEx2Return   *ebpf.ProgramSpec `ebpf:"obs_write_ex2_return"`
	ObsWriteExEntry     *ebpf.ProgramSpec `ebpf:"obs_write_ex_entry"`
	ObsWriteExReturn    *ebpf.ProgramSpec `ebpf:"obs_write_ex_return"`
	ObsWriteReturn      *ebpf.ProgramSpec `ebpf:"obs_write_return"`
	ObsWritev           *ebpf.ProgramSpec `ebpf:"obs_writev"`
}

// metaMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metaMapSpecs struct {
	AllowedProcesses *ebpf.MapSpec `ebpf:"allowed_processes"`
	Attempts         *ebpf.MapSpec `ebpf:"attempts"`
	Bindings         *ebpf.MapSpec `ebpf:"bindings"`
	Discovered       *ebpf.MapSpec `ebpf:"discovered"`
	Discoveries      *ebpf.MapSpec `ebpf:"discoveries"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	Forking          *ebpf.MapSpec `ebpf:"forking"`
	Generations      *ebpf.MapSpec `ebpf:"generations"`
	Handles          *ebpf.MapSpec `ebpf:"handles"`
	Inflight         *ebpf.MapSpec `ebpf:"inflight"`
	Namespaces       *ebpf.MapSpec `ebpf:"namespaces"`
	Operations       *ebpf.MapSpec `ebpf:"operations"`
	Sequences        *ebpf.MapSpec `ebpf:"sequences"`
	Sockets          *ebpf.MapSpec `ebpf:"sockets"`
	Stats            *ebpf.MapSpec `ebpf:"stats"`
	UnmatchedAt      *ebpf.MapSpec `ebpf:"unmatched_at"`
	Unmeasurable     *ebpf.MapSpec `ebpf:"unmeasurable"`
}

// metaVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metaVariableSpecs struct {
}

// metaObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMetaObjects or ebpf.CollectionSpec.LoadAndAssign.
type metaObjects struct {
	metaPrograms
	metaMaps
	metaVariables
}

func (o *metaObjects) Close() error {
	return _MetaClose(
		&o.metaPrograms,
		&o.metaMaps,
	)
}

// metaMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMetaObjects or ebpf.CollectionSpec.LoadAndAssign.
type metaMaps struct {
	AllowedProcesses *ebpf.Map `ebpf:"allowed_processes"`
	Attempts         *ebpf.Map `ebpf:"attempts"`
	Bindings         *ebpf.Map `ebpf:"bindings"`
	Discovered       *ebpf.Map `ebpf:"discovered"`
	Discoveries      *ebpf.Map `ebpf:"discoveries"`
	Events           *ebpf.Map `ebpf:"events"`
	Forking          *ebpf.Map `ebpf:"forking"`
	Generations      *ebpf.Map `ebpf:"generations"`
	Handles          *ebpf.Map `ebpf:"handles"`
	Inflight         *ebpf.Map `ebpf:"inflight"`
	Namespaces       *ebpf.Map `ebpf:"namespaces"`
	Operations       *ebpf.Map `ebpf:"operations"`
	Sequences        *ebpf.Map `ebpf:"sequences"`
	Sockets          *ebpf.Map `ebpf:"sockets"`
	Stats            *ebpf.Map `ebpf:"stats"`
	UnmatchedAt      *ebpf.Map `ebpf:"unmatched_at"`
	Unmeasurable     *ebpf.Map `ebpf:"unmeasurable"`
}

func (m *metaMaps) Close() error {
	return _MetaClose(
		m.AllowedProcesses,
		m.Attempts,
		m.Bindings,
		m.Discovered,
		m.Discoveries,
		m.Events,
		m.Forking,
		m.Generations,
		m.Handles,
		m.Inflight,
		m.Namespaces,
		m.Operations,
		m.Sequences,
		m.Sockets,
		m.Stats,
		m.UnmatchedAt,
		m.Unmeasurable,
	)
}

// metaVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMetaObjects or ebpf.CollectionSpec.LoadAndAssign.
type metaVariables struct {
}

// metaPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMetaObjects or ebpf.CollectionSpec.LoadAndAssign.
type metaPrograms struct {
	ObsAcceptReturn     *ebpf.Program `ebpf:"obs_accept_return"`
	ObsClose            *ebpf.Program `ebpf:"obs_close"`
	ObsConnect          *ebpf.Program `ebpf:"obs_connect"`
	ObsDup2             *ebpf.Program `ebpf:"obs_dup2"`
	ObsExec             *ebpf.Program `ebpf:"obs_exec"`
	ObsExit             *ebpf.Program `ebpf:"obs_exit"`
	ObsFork             *ebpf.Program `ebpf:"obs_fork"`
	ObsForkEntry        *ebpf.Program `ebpf:"obs_fork_entry"`
	ObsForkReturn       *ebpf.Program `ebpf:"obs_fork_return"`
	ObsFreeEntry        *ebpf.Program `ebpf:"obs_free_entry"`
	ObsInet6Recvmsg     *ebpf.Program `ebpf:"obs_inet6_recvmsg"`
	ObsInet6Sendmsg     *ebpf.Program `ebpf:"obs_inet6_sendmsg"`
	ObsInetRecvmsg      *ebpf.Program `ebpf:"obs_inet_recvmsg"`
	ObsInetSendmsg      *ebpf.Program `ebpf:"obs_inet_sendmsg"`
	ObsRead             *ebpf.Program `ebpf:"obs_read"`
	ObsReadEarlyEntry   *ebpf.Program `ebpf:"obs_read_early_entry"`
	ObsReadEarlyReturn  *ebpf.Program `ebpf:"obs_read_early_return"`
	ObsReadEntry        *ebpf.Program `ebpf:"obs_read_entry"`
	ObsReadExEntry      *ebpf.Program `ebpf:"obs_read_ex_entry"`
	ObsReadExReturn     *ebpf.Program `ebpf:"obs_read_ex_return"`
	ObsReadReturn       *ebpf.Program `ebpf:"obs_read_return"`
	ObsReadv            *ebpf.Program `ebpf:"obs_readv"`
	ObsRecvfrom         *ebpf.Program `ebpf:"obs_recvfrom"`
	ObsRecvmsg          *ebpf.Program `ebpf:"obs_recvmsg"`
	ObsRwVerifyArea     *ebpf.Program `ebpf:"obs_rw_verify_area"`
	ObsSendmsg          *ebpf.Program `ebpf:"obs_sendmsg"`
	ObsSendto           *ebpf.Program `ebpf:"obs_sendto"`
	ObsSocketReturn     *ebpf.Program `ebpf:"obs_socket_return"`
	ObsSysEnter         *ebpf.Program `ebpf:"obs_sys_enter"`
	ObsSysExit          *ebpf.Program `ebpf:"obs_sys_exit"`
	ObsWrite            *ebpf.Program `ebpf:"obs_write"`
	ObsWriteEarlyEntry  *ebpf.Program `ebpf:"obs_write_early_entry"`
	ObsWriteEarlyReturn *ebpf.Program `ebpf:"obs_write_early_return"`
	ObsWriteEntry       *ebpf.Program `ebpf:"obs_write_entry"`
	ObsWriteEx2Entry    *ebpf.Program `ebpf:"obs_write_ex2_entry"`
	ObsWriteEx2Return   *ebpf.Program `ebpf:"obs_write_ex2_return"`
	ObsWriteExEntry     *ebpf.Program `ebpf:"obs_write_ex_entry"`
	ObsWriteExReturn    *ebpf.Program `ebpf:"obs_write_ex_return"`
	ObsWriteReturn      *ebpf.Program `ebpf:"obs_write_return"`
	ObsWritev           *ebpf.Program `ebpf:"obs_writev"`
}

func (p *metaPrograms) Close() error {
	return _MetaClose(
		p.ObsAcceptReturn,
		p.ObsClose,
		p.ObsConnect,
		p.ObsDup2,
		p.ObsExec,
		p.ObsExit,
		p.ObsFork,
		p.ObsForkEntry,
		p.ObsForkReturn,
		p.ObsFreeEntry,
		p.ObsInet6Recvmsg,
		p.ObsInet6Sendmsg,
		p.ObsInetRecvmsg,
		p.ObsInetSendmsg,
		p.ObsRead,
		p.ObsReadEarlyEntry,
		p.ObsReadEarlyReturn,
		p.ObsReadEntry,
		p.ObsReadExEntry,
		p.ObsReadExReturn,
		p.ObsReadReturn,
		p.ObsReadv,
		p.ObsRecvfrom,
		p.ObsRecvmsg,
		p.ObsRwVerifyArea,
		p.ObsSendmsg,
		p.ObsSendto,
		p.ObsSocketReturn,
		p.ObsSysEnter,
		p.ObsSysExit,
		p.ObsWrite,
		p.ObsWriteEarlyEntry,
		p.ObsWriteEarlyReturn,
		p.ObsWriteEntry,
		p.ObsWriteEx2Entry,
		p.ObsWriteEx2Return,
		p.ObsWriteExEntry,
		p.ObsWriteExReturn,
		p.ObsWriteReturn,
		p.ObsWritev,
	)
}

func _MetaClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed meta_arm64_bpfel.o
var _MetaBytes []byte
